name: childrensafe_parent
description: ChildrenSafe — app del tutor (padre/madre/tutor).
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  childrensafe_shared:
    path: ../shared
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
